Genre.create({ name: "Science" })
Genre.create({ name: "Children's" })
Genre.create({ name: "Maritime" })
Genre.create({ name: "Natural History" })
Genre.create({ name: "Modern" })
Genre.create({ name: "Memorial" })
