scream = User.create(username: "Scream", first_name:"Ernesto", last_name: "Camou", role: "admin", email: "ok999@hotmail.com", password: "123456")
lazycat05 = User.create(username: "LazyCat05", first_name:"Tim", last_name: "Hollis", role: "admin", email: "tim@tim.com", password: "123456")
natdouglas = User.create(username: "natdouglas", first_name:"Natalie", last_name: "Douglas", role: "admin", email: "natalie@gmail.com", password: "123456")
meghas = User.create(username: "meghas", first_name:"Megha", last_name: "Bellary", role: "admin", email: "megha4@hotmail.com", password: "123456")
themaikol = User.create(username: "themaikol", first_name:"Maikol", last_name: "Etcheverry", role: "admin", email: "maikol@hotmail.com", password: "123456")

science=Genre.create({ name: "Science" })
childrens=Genre.create({ name: "Children's" })
maritime=Genre.create({ name: "Maritime" })
natural_history=Genre.create({ name: "Natural History" })
modern=Genre.create({ name: "Modern" })
memorial=Genre.create({ name: "Memorial" })
garden_park=Genre.create({ name: "Garden/Park" })
history=Genre.create({name: "History"})
off_beaten_path=Genre.create({ name: "Off the Beaten Path" })

heritage_museums_and_gardens=Museum.create(name:"Heritage Museums and Gardens", location:"67 Grove Street, Sandwich, MA 02563", description:"Engaging Exhibit and 100 acres of gardens and nature trails", founding_date:"01/03/2010", url: "https://heritagemuseumsandgardens.org/", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/hereitage_museums_and_gardens.png")
boston_childrens_museum=Museum.create(name:"Boston Children's Museum", location: "308 Congress St., Boston, MA 02210", description:"Boston Children’s Museum is the second oldest, and one of the most influential children’s museums in the world.", founding_date:"01/01/1913", url: "http://www.bostonchildrensmuseum.org/", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/boston_childrens_museum.jpg")
mfa_museum=Museum.create(name:"Museum of Fine Arts", location:"465 Huntington Avenue, Boston, MA 02115", description:"The MFA is one of the most comprehensive art museums in the world; the collection encompasses nearly 450,000 works of art.", founding_date:"07/04/1876", url: "http://www.mfa.org/", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/mfa_boston.jpg")
harvard_museum_of_natural_history=Museum.create(name:"Harvard Museum of Natural History", location:"26 Oxford Street, Cambridge, MA 02138", description:"The most visited museum on the historic Harvard University campus, the Harvard Museum of Natural History displays some 12,000 specimens, including dinosaurs, rare minerals, hundreds of mammals, birds, and Harvard's world famous Blaschka 'Glass Flowers'.", url:"https://hmnh.harvard.edu/", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/harvard_museum_natural_history.png")
adams_national_historical_park=Museum.create(name:"Adams National Historical Park", location:"1250 Hancock Street, Adams National Historical Park Visitor Center, Quincy, MA 02169", description:"Travel back in time at the Adams National Historical Park, where you'll visit the birthplaces of not one, but two U.S. presidents: John Adams and his son, John Quincy Adams.", url:"https://www.nps.gov/adam/index.htm", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/adams_national_park.png")
decordova_museum=Museum.create(name:"deCordova Sculpture Park and Museum", location:"51 Sandy Pond Rd., Lincoln, MA 01773", description:"Just 20 miles west of Boston, deCordova Sculpture Park and Museum is dedicated to fostering the creation and exploration of contemporary sculpture and art through a dynamic slate of rotating exhibitions, innovative learning opportunities, a constantly changing 30-acre landscape of large-scale, outdoor, modern and contemporary sculpture, and site-specific installations.", url:"https://decordova.org/", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/decordova_museum.png")
museum_bad_art=Museum.create(name:"Museum of Bad Art", location:"Somerville Theater, 55 Davis Square, Somerville, MA 02144", description:"The world's only museum dedicated to the collection, preservation, exhibition, and celebration of bad art in all its forms. As the only museum dedicated to bring the best bad art to the widest of audiences, we felt morally compelled to explore new, more creative ways of bringing this priceless collection of quality bad art to a global audience.", url:"http://museumofbadart.org/", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/museum_of_bad_arts.png")
cape_cod_maritime_museum=Museum.create(name:"Cape Cod Maritime Museum", location:"135 South Street, Hyannis, MA 02601", description:"The Cape Cod Maritime Museum in Hyannis, MA showcases the Cape's maritime history with a variety of permanent and temporary exhibits.", url:"http://www.capecodmaritimemuseum.org/", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/cape_cod_maritime_museum.png")
worcester_art_museum=Museum.create(name:"Worcester Art Museum", location:"55 Salisbury St, Worcester, MA 01609", description:"The Worcester Art Museum, which opened to the public in 1898, invites you to view the more than 37,000+ piece encyclopedic collection of paintings, sculpture, decorative arts, photography, prints, drawings, arms, armor and new media.", founding_date: "1898", url: "http://www.worcesterart.org/", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/worcester_art_museum.png"  )
memorial_hall_museum=Museum.create(name:"Memorial Hall museum", location: "Memorial Street, Deerfield, M", description: "Memorial Hall is one of New England’s oldest museums. When Deerfield Academy’s original 1798 school building became available, antiquarian George Sheldon organized the collection of artifacts he was assembling, and in 1880 Memorial Hall opened. The museum’s extraordinary collection of furnishings, paintings, textiles, and Indian artifacts is “the finest collection of local antiquities in New England” and is one of America’s oldest museums.", url: "https://deerfield-ma.org/about/memorial-hall-museum/", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/memorial_hall.png")
ernest_hemingway_collection= Museum.create(name:"Ernest Hemingway Collection", location:"220 William T Morrissey Blvd.
Boston, MA 02125", description:"There is very little weird about Ernest Hemingway’s belongings kept at the J.F.K Library. What is weird is the story of how they got there, which is covered by the museum.",url:"www.jfklibrary.org", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/ernest.png")
warren_anatomical_museum=Museum.create(name:"Warren Anatomical Museum",location:"10 Shattuck St.Boston, MA 02115",description: "The museum’s current collection includes an ether inhaler, the skull of Phineas Gage, whose head injuries and survival were famous, numerous skeletons and preserved bits of people, both normal and deformed.",url:"www.countway.harvard.edu", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/warren_anatomical_museum.png")
boston_tea_party_museum=Museum.create(name:"Boston Tea Party Ships and Museum", location:"306 Congress Street, Boston, MA 02210", description:"At the Boston Tea Party Ships and Museum, you can be a part of the famous event that forever changed the course of American History! It's more than a stroll through historic artifacts - it's an adventure!", url:"https://www.bostonteapartyship.com/", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/boston_tea_party_museum.jpg")
castle_hill_museum=Museum.create(name:"Castle Hill on Crane Estate", location:"290 Argilla Rd., Ipswich, MA 01938", description:"Experience the grandeur of a seaside estate and its marvelously landscaped grounds, notable for a broad, undulating lawn running down to the shore. Castle Hill has come to exemplify the American Country Place Era with its farm and estate buildings, designed grounds and gardens, and diverse natural areas.", url:"http://www.thetrustees.org/places-to-visit/north-shore/castle-hill-crane.html", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/castle_hill.png")
national_black_doll=Museum.create(name:"The National Black Doll Museum of History & Culture", location:"288 N. Main Street, Mansfield, MA 02048", description:"The National Black Doll Museum of History & Culture is the only museum in the country who teaches black history through the eyes of a doll collector.", url:"http://nbdmhc.org/", image_url:"https://s3.amazonaws.com/launch-academy-museumist/museum_images/black_doll.png")

MuseumGenre.create(museum: warren_anatomical_museum, genre:science)
MuseumGenre.create(museum: warren_anatomical_museum, genre:off_beaten_path)
MuseumGenre.create(museum:heritage_museums_and_gardens, genre:natural_history)
MuseumGenre.create(museum:heritage_museums_and_gardens, genre:garden_park)
MuseumGenre.create(museum:boston_childrens_museum, genre:science)
MuseumGenre.create(museum:boston_childrens_museum, genre:childrens)
MuseumGenre.create(museum:mfa_museum, genre:modern)
MuseumGenre.create(museum:harvard_museum_of_natural_history, genre:natural_history)
MuseumGenre.create(museum:adams_national_historical_park, genre:natural_history)
MuseumGenre.create(museum:adams_national_historical_park, genre:garden_park)
MuseumGenre.create(museum:decordova_museum, genre:modern)
MuseumGenre.create(museum:museum_bad_art, genre:modern)
MuseumGenre.create(museum:museum_bad_art, genre:off_beaten_path)
MuseumGenre.create(museum:cape_cod_maritime_museum, genre:maritime)
MuseumGenre.create(museum:worcester_art_museum,genre:history)
MuseumGenre.create(museum:memorial_hall_museum,genre:memorial)
MuseumGenre.create(museum:ernest_hemingway_collection,genre:off_beaten_path)
MuseumGenre.create(museum:boston_tea_party_museum, genre: maritime)
MuseumGenre.create(museum:castle_hill_museum, genre: garden_park)
MuseumGenre.create(museum:national_black_doll, genre:off_beaten_path)
MuseumGenre.create(museum:national_black_doll, genre:childrens)

Review.create(body:"it was awful", rating: 1, user: scream, museum: heritage_museums_and_gardens )
Review.create(body:"it was lovely", rating: 4, user: meghas, museum: heritage_museums_and_gardens )
Review.create(body:"it was medium", rating: 3, user: themaikol, museum: heritage_museums_and_gardens )
Review.create(body:"it was delightful", rating: 5, user: natdouglas, museum: boston_childrens_museum )
Review.create(body:"it was magnificent", rating: 5, user: lazycat05, museum: boston_childrens_museum )
Review.create(body:"COMING BACK TOMORROW!!", rating: 5, user: natdouglas, museum: mfa_museum )
Review.create(body:"don't ever come here", rating: 1, user: meghas, museum: harvard_museum_of_natural_history )
Review.create(body:"Go now", rating: 4, user: themaikol, museum: adams_national_historical_park )
Review.create(body:"It was a strange experience", rating: 3, user: scream, museum: adams_national_historical_park )
Review.create(body:"It was a mindful experience", rating: 2, user: lazycat05, museum: decordova_museum )
Review.create(body:"I love this place", rating: 5, user: themaikol, museum: decordova_museum )
Review.create(body:"It was an awesome place", rating: 5, user: scream, museum: decordova_museum )
Review.create(body:"Great museum", rating: 4, user: meghas, museum: decordova_museum )
Review.create(body:"Top place", rating: 5, user: natdouglas, museum: museum_bad_art )
Review.create(body:"bottom place", rating: 1, user: meghas, museum: museum_bad_art )
